//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShenmueHDTools.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShenmueHDTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 131100 
        ///\1ST_READ.BIN 2699828 
        ///\DISCNUM.BIN 2048 
        ///\FIGHT\EN_RYOU.BIN 7596 
        ///\FONT\ASCII.PVR 6172 
        ///\HANGON\HANGON.BIN 5378124 
        ///\HANGON\HANGON.EMU 849420 
        ///\HARRIER\HARRIER.PKS 2288336 
        ///\MISC\AICADRV.BIN 59264 
        ///\MISC\BATTLE.GZ 34230 
        ///\MISC\BATTLE_E.GZ 34230 
        ///\MISC\BATTLE_F.GZ 33722 
        ///\MISC\BATTLE_G.GZ 34928 
        ///\MISC\BATTLE_S.GZ 34754 
        ///\MISC\BGM110.SND 632148 
        ///\MISC\CM_D000.BIN 629716 
        ///\MISC\CM_JOMO.BIN 21064 
        ///\MISC\CM_MFSY.BIN 329144 
        ///\MISC\COLD.BIN 2414064 
        ///\MISC\COLDINIT.PKF 108715 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string B_D1 {
            get {
                return ResourceManager.GetString("B_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 131100 
        ///\1ST_READ.BIN 2699828 
        ///\DISCNUM.BIN 2048 
        ///\FIGHT\EN_RYOU.BIN 7596 
        ///\FONT\ASCII.PVR 6172 
        ///\HANGON\HANGON.BIN 5378124 
        ///\HANGON\HANGON.EMU 849420 
        ///\HARRIER\HARRIER.PKS 2288336 
        ///\MISC\AICADRV.BIN 59264 
        ///\MISC\BATTLE.GZ 34230 
        ///\MISC\BATTLE_E.GZ 34230 
        ///\MISC\BATTLE_F.GZ 33722 
        ///\MISC\BATTLE_G.GZ 34928 
        ///\MISC\BATTLE_S.GZ 34754 
        ///\MISC\BGM110.SND 632148 
        ///\MISC\CM_D000.BIN 629716 
        ///\MISC\CM_JOMO.BIN 21064 
        ///\MISC\CM_MFSY.BIN 329144 
        ///\MISC\COLD.BIN 2414064 
        ///\MISC\COLDINIT.PKF 108715 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string B_D2 {
            get {
                return ResourceManager.GetString("B_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 131100 
        ///\1ST_READ.BIN 2699828 
        ///\DISCNUM.BIN 2048 
        ///\FIGHT\EN_RYOU.BIN 7596 
        ///\FONT\ASCII.PVR 6172 
        ///\HANGON\HANGON.BIN 5378124 
        ///\HANGON\HANGON.EMU 849420 
        ///\HARRIER\HARRIER.PKS 2288336 
        ///\MISC\AICADRV.BIN 59264 
        ///\MISC\BATTLE.GZ 34230 
        ///\MISC\BATTLE_E.GZ 34230 
        ///\MISC\BATTLE_F.GZ 33722 
        ///\MISC\BATTLE_G.GZ 34928 
        ///\MISC\BATTLE_S.GZ 34754 
        ///\MISC\BGM110.SND 632148 
        ///\MISC\CM_D000.BIN 629716 
        ///\MISC\CM_JOMO.BIN 21064 
        ///\MISC\CM_MFSY.BIN 329144 
        ///\MISC\COLD.BIN 2414064 
        ///\MISC\COLDINIT.PKF 108715 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string B_D3 {
            get {
                return ResourceManager.GetString("B_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 174796 
        ///\1ST_READ.BIN 5054464 
        ///\AICADRV.BIN 63432 
        ///\MON.BIN 65552 
        ///\MOVIE.BIN 405760 
        ///\RELOAD.BIN 660736 
        ///\RPG.BIN 4988928 
        ///\SNDPACK.BIN 97392 
        ///\SP_01.SFD 14462976 
        ///\SP_11.SFD 58628096 
        ///\SP_17.SFD 78546944 
        ///\SP_18.SFD 34596864 
        ///\SP_19.SFD 58929152 
        ///\FONT\ASCII.PVR 6172 
        ///\FONT\DC_KANA.FON 7680 
        ///\FONT\DC_KANJI.FON 351270 
        ///\FONT\RYOU.FON 351270 
        ///\FONT\WAZA.FON 351270 
        ///\MISC\AICADRV.BIN 59264 
        ///\MISC\ASCII.PVR 6172 
        ///\MISC\BATTLE.GZ 36392 
        ///\MISC\BGM110.SND 632148 
        ///\MISC\CM_D000.B [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string B_PASS {
            get {
                return ResourceManager.GetString("B_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NAME;DESCRIPTION
        ///019RN;Goro’s attacked, Ryo is QTE ambushed by five people.
        ///01AYU;End of cutscene where Gui Zhang teaches Ryo a move
        ///01BEDA;Bad ending: Lan Di returns to Hazuki Residence (all disks)
        ///01BEDB;Bad Ending: Shenhua warning (all disks)
        ///01BEDB;Bad ending: Shenhua warning (all disks)
        ///01BIKE;Ryo asks for Naoyuki’s bike at Sakuragaoka.
        ///01BIKEB;“I wish” song cutscene: “Thanks for saving me.”
        ///01BNK;“Guess Hong Kong’s out.”
        ///01BTU;Nozomi brings flowers to Ryo’s house
        ///01BUS;Japanese text, no need [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string desc_audio_sm1 {
            get {
                return ResourceManager.GetString("desc_audio_sm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Character Name;ID;Model Name;Major Location;Major Store;BIO                              |
        /// Akemi Sato ; AKMI ; HOS_L; Dobuita; Bar Yokosuka ; [Akemi Sato ](http://shenmue.neoseeker.com/wiki/Akemi_Sato);
        /// Akihiro Ishida ; ISDA ; JMC_L;Harbor;Outside Worker; [Akihiro Ishida ](http://shenmue.neoseeker.com/wiki/Akihiro_Ishida) ;
        /// Akihisa Shigematsu ;; NVC_S;Harbor;Mad Angels; [Mad Angels](http://shenmue.neoseeker.com/wiki/Mad_Angels#Mad_Angels_Members) ;
        /// Akihito Anzai; TKNB ; PAN_L; Dobuita;Residence ; [A [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string desc_chars_sm1 {
            get {
                return ResourceManager.GetString("desc_chars_sm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NAME;ID;LOCATION;APPERANCE;ENTRY POINTS
        ///Abe Store Candy Shop ;JABE ;Sakuragaoka ;SCENE 01 ; 
        ///Ajiichi Chinese Restaurant ;DCHA ;Dobuita ;SCENE 01 ; 
        ///Alpha Trading Office ;MFSY --&gt; ALPHA (IPAC) ;Harbor ;SCENE 03 ;N/A Sub IPAC Data for Harbor 
        ///Antique Shop ;DKTY ;Dobuita ;SCENE 01 ; 
        ///Asia Travel Company ;ARAR ;Dobuita ;SCENE 01 ;ALL Ticket Cutscene 
        ///Asia Travel Company ;DAZA ;Dobuita ;SCENE 01 ;Unknown duplicate 
        ///Bar Linda ;DSLI ;Dobuita ;SCENE 01 ; 
        ///Bar Yokosuka ;DBYO ;Dobuita ;SCENE 01 ; 
        ///Bob&apos;s Pizz [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string desc_maps_sm1 {
            get {
                return ResourceManager.GetString("desc_maps_sm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 174796 
        ///\1ST_READ.BIN 3196456 
        ///\DISCNUM.BIN 2048 
        ///\BURNER\AB2.BIN 719286 
        ///\BURNER\AB2.SND 1894368 
        ///\BURNER\AB2_TEX.BIN 3145728 
        ///\BURNER\PROG.BIN 524288 
        ///\EVENT\DGCT.EV3 22612 
        ///\EVENT\JUMP.EV3 31320 
        ///\EVENT\QESC.EV3 21304 
        ///\FRENCH\BUNKI.BIN 2176 
        ///\FRENCH\DISCCHG1.GZ 732460 
        ///\FRENCH\DISCCHG2.GZ 776580 
        ///\FRENCH\DISCCHG3.GZ 892685 
        ///\FRENCH\DISCCHG4.GZ 674138 
        ///\FRENCH\MEMODATA.BIN 32036 
        ///\FRENCH\MEMOFLG.BIN 2700 
        ///\FRENCH\RESUME02.SPR 18480 
        ///\FRENCH\RESUME03.SPR 18480 
        ///\FRENCH\TCOMM [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string EU_2_D1 {
            get {
                return ResourceManager.GetString("EU_2_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 174796 
        ///\1ST_READ.BIN 3196456 
        ///\DISCNUM.BIN 2048 
        ///\EVENT\DGCT.EV3 22612 
        ///\EVENT\JUMP.EV3 31320 
        ///\EVENT\QESC.EV3 21304 
        ///\FRENCH\BUNKI.BIN 2176 
        ///\FRENCH\DISCCHG1.GZ 732460 
        ///\FRENCH\DISCCHG2.GZ 776580 
        ///\FRENCH\DISCCHG3.GZ 892685 
        ///\FRENCH\DISCCHG4.GZ 674138 
        ///\FRENCH\MEMODATA.BIN 32036 
        ///\FRENCH\MEMOFLG.BIN 2700 
        ///\FRENCH\RESUME02.SPR 18480 
        ///\FRENCH\RESUME03.SPR 18480 
        ///\FRENCH\TCOMMON.GZ 34339 
        ///\FRENCH\TITLE.GZ 573410 
        ///\FRENCH\TVTXT.SPR 67632 
        ///\FRENCH\VM_A01.GZ 27807 
        ///\FRENCH\VM_A03. [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string EU_2_D2 {
            get {
                return ResourceManager.GetString("EU_2_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 174796 
        ///\1ST_READ.BIN 3196456 
        ///\DISCNUM.BIN 2048 
        ///\BURNER\AB2.BIN 719286 
        ///\BURNER\AB2.SND 1894368 
        ///\BURNER\AB2_TEX.BIN 3145728 
        ///\BURNER\PROG.BIN 524288 
        ///\EVENT\DGCT.EV3 22612 
        ///\EVENT\JUMP.EV3 31320 
        ///\EVENT\QESC.EV3 21304 
        ///\FRENCH\BUNKI.BIN 2176 
        ///\FRENCH\DISCCHG1.GZ 732460 
        ///\FRENCH\DISCCHG2.GZ 776580 
        ///\FRENCH\DISCCHG3.GZ 892685 
        ///\FRENCH\DISCCHG4.GZ 674138 
        ///\FRENCH\MEMODATA.BIN 32036 
        ///\FRENCH\MEMOFLG.BIN 2700 
        ///\FRENCH\RESUME02.SPR 18480 
        ///\FRENCH\RESUME03.SPR 18480 
        ///\FRENCH\TCOMM [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string EU_2_D3 {
            get {
                return ResourceManager.GetString("EU_2_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 174796 
        ///\1ST_READ.BIN 3196456 
        ///\DISCNUM.BIN 2048 
        ///\BURNER\AB2.BIN 719286 
        ///\BURNER\AB2.SND 1894368 
        ///\BURNER\AB2_TEX.BIN 3145728 
        ///\BURNER\PROG.BIN 524288 
        ///\EVENT\DGCT.EV3 22612 
        ///\EVENT\JUMP.EV3 31320 
        ///\EVENT\QESC.EV3 21304 
        ///\FRENCH\BUNKI.BIN 2176 
        ///\FRENCH\DISCCHG1.GZ 732460 
        ///\FRENCH\DISCCHG2.GZ 776580 
        ///\FRENCH\DISCCHG3.GZ 892685 
        ///\FRENCH\DISCCHG4.GZ 674138 
        ///\FRENCH\MEMODATA.BIN 32036 
        ///\FRENCH\MEMOFLG.BIN 2700 
        ///\FRENCH\RESUME02.SPR 18480 
        ///\FRENCH\RESUME03.SPR 18480 
        ///\FRENCH\TCOMM [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string EU_2_PASS {
            get {
                return ResourceManager.GetString("EU_2_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 131100 
        ///\1ST_READ.BIN 2755492 
        ///\DISCNUM.BIN 2048 
        ///\FIGHT\EN_RYOU.BIN 7596 
        ///\FONT\ASCII.PVR 6172 
        ///\HANGON\HANGON.BIN 5378124 
        ///\HANGON\HANGON.EMU 849420 
        ///\HARRIER\HARRIER.PKS 2288336 
        ///\MISC\AICADRV.BIN 59264 
        ///\MISC\BATTLE.GZ 34230 
        ///\MISC\BATTLE_E.GZ 34230 
        ///\MISC\BATTLE_F.GZ 33722 
        ///\MISC\BATTLE_G.GZ 34928 
        ///\MISC\BATTLE_S.GZ 34754 
        ///\MISC\BGM110.SND 632148 
        ///\MISC\CM_D000.BIN 629716 
        ///\MISC\CM_JOMO.BIN 21064 
        ///\MISC\CM_MFSY.BIN 329144 
        ///\MISC\COLD.BIN 2414064 
        ///\MISC\COLDINIT.PKF 108715 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string EU_D1 {
            get {
                return ResourceManager.GetString("EU_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 131100 
        ///\1ST_READ.BIN 2755492 
        ///\DISCNUM.BIN 2048 
        ///\FIGHT\EN_RYOU.BIN 7596 
        ///\FONT\ASCII.PVR 6172 
        ///\HANGON\HANGON.BIN 5378124 
        ///\HANGON\HANGON.EMU 849420 
        ///\HARRIER\HARRIER.PKS 2288336 
        ///\MISC\AICADRV.BIN 59264 
        ///\MISC\BATTLE.GZ 34230 
        ///\MISC\BATTLE_E.GZ 34230 
        ///\MISC\BATTLE_F.GZ 33722 
        ///\MISC\BATTLE_G.GZ 34928 
        ///\MISC\BATTLE_S.GZ 34754 
        ///\MISC\BGM110.SND 632148 
        ///\MISC\CM_D000.BIN 629716 
        ///\MISC\CM_JOMO.BIN 21064 
        ///\MISC\CM_MFSY.BIN 329144 
        ///\MISC\COLD.BIN 2414064 
        ///\MISC\COLDINIT.PKF 108715 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string EU_D2 {
            get {
                return ResourceManager.GetString("EU_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.BMP 262282 
        ///\0GDTEX.PVR 131100 
        ///\1ST_READ.BIN 2755492 
        ///\ABSTRACT.TXT 0 
        ///\AUTORUN.INF 50 
        ///\BIBLIOGR.TXT 0 
        ///\COPYRIGH.TXT 19 
        ///\DISCNUM.BIN 2048 
        ///\WARNING.MP3 262340 
        ///\FIGHT\EN_RYOU.BIN 7596 
        ///\FONT\ASCII.PVR 6172 
        ///\HANGON\HANGON.BIN 5378124 
        ///\HANGON\HANGON.EMU 849420 
        ///\HARRIER\HARRIER.PKS 2288336 
        ///\MISC\AICADRV.BIN 59264 
        ///\MISC\BATTLE.GZ 34230 
        ///\MISC\BATTLE_E.GZ 34230 
        ///\MISC\BATTLE_F.GZ 33722 
        ///\MISC\BATTLE_G.GZ 34928 
        ///\MISC\BATTLE_S.GZ 34754 
        ///\MISC\BGM110.SND 632148 
        ///\MISC\CM_D000. [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string EU_D3 {
            get {
                return ResourceManager.GetString("EU_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.BMP 262282 
        ///\0GDTEX.PVR 131100 
        ///\1ST_READ.BIN 5054464 
        ///\ABSTRACT.TXT 0 
        ///\AICADRV.BIN 63432 
        ///\AUTORUN.INF 50 
        ///\BIBLIOGR.TXT 0 
        ///\COPYRIGH.TXT 19 
        ///\MON.BIN 65552 
        ///\MOVIE.BIN 400128 
        ///\RELOAD.BIN 660736 
        ///\RPG.BIN 4988928 
        ///\SNDPACK.BIN 97392 
        ///\SP_01.SFD 3831808 
        ///\SP_11.SFD 17836032 
        ///\SP_17.SFD 24246272 
        ///\SP_18.SFD 10852352 
        ///\SP_19.SFD 17676288 
        ///\WARNING.MP3 2385459 
        ///\FONT\ASCII.PVR 6172 
        ///\FONT\DC_KANA.FON 7680 
        ///\FONT\DC_KANJI.FON 351270 
        ///\FONT\RYOU.FON 351270 
        ///\FONT\WAZA.FON 351270  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string EU_PASS {
            get {
                return ResourceManager.GetString("EU_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] gfx {
            get {
                object obj = ResourceManager.GetObject("gfx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 174796 
        ///\1ST_READ.BIN 2709860 
        ///\DISCNUM.BIN 2048 
        ///\FIGHT\EN_RYOU.BIN 7596 
        ///\FONT\ASCII.PVR 6172 
        ///\HANGON\HANGON.BIN 5378124 
        ///\HANGON\HANGON.EMU 849420 
        ///\HARRIER\HARRIER.PKS 2288336 
        ///\MISC\AICADRV.BIN 59264 
        ///\MISC\BATTLE.GZ 36392 
        ///\MISC\BGM110.SND 632148 
        ///\MISC\CM_D000.BIN 629716 
        ///\MISC\CM_JOMO.BIN 21064 
        ///\MISC\CM_MFSY.BIN 329144 
        ///\MISC\COLD.BIN 2757072 
        ///\MISC\COLDINIT.PKF 108715 
        ///\MISC\COLDINIT.PKS 1700469 
        ///\MISC\DC_KANA.FON 7680 
        ///\MISC\DC_KANJI.FON 351270 
        ///\MISC\MODELS.PKF 10 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string JAP_D1 {
            get {
                return ResourceManager.GetString("JAP_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 174796 
        ///\1ST_READ.BIN 2709860 
        ///\DISCNUM.BIN 2048 
        ///\FIGHT\EN_RYOU.BIN 7596 
        ///\FONT\ASCII.PVR 6172 
        ///\HANGON\HANGON.BIN 5378124 
        ///\HANGON\HANGON.EMU 849420 
        ///\HARRIER\HARRIER.PKS 2288336 
        ///\MISC\AICADRV.BIN 59264 
        ///\MISC\BATTLE.GZ 36392 
        ///\MISC\BGM110.SND 632148 
        ///\MISC\CM_D000.BIN 629716 
        ///\MISC\CM_JOMO.BIN 21064 
        ///\MISC\CM_MFSY.BIN 329144 
        ///\MISC\COLD.BIN 2757072 
        ///\MISC\COLDINIT.PKF 108715 
        ///\MISC\COLDINIT.PKS 1700469 
        ///\MISC\DC_KANA.FON 7680 
        ///\MISC\DC_KANJI.FON 351270 
        ///\MISC\MODELS.PKF 10 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string JAP_D2 {
            get {
                return ResourceManager.GetString("JAP_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 174796 
        ///\1ST_READ.BIN 2709860 
        ///\DISCNUM.BIN 2048 
        ///\FIGHT\EN_RYOU.BIN 7596 
        ///\FONT\ASCII.PVR 6172 
        ///\HANGON\HANGON.BIN 5378124 
        ///\HANGON\HANGON.EMU 849420 
        ///\HARRIER\HARRIER.PKS 2288336 
        ///\MISC\AICADRV.BIN 59264 
        ///\MISC\BATTLE.GZ 36392 
        ///\MISC\BGM110.SND 632148 
        ///\MISC\CM_D000.BIN 629716 
        ///\MISC\CM_JOMO.BIN 21064 
        ///\MISC\CM_MFSY.BIN 329144 
        ///\MISC\COLD.BIN 2757072 
        ///\MISC\COLDINIT.PKF 108715 
        ///\MISC\COLDINIT.PKS 1700469 
        ///\MISC\DC_KANA.FON 7680 
        ///\MISC\DC_KANJI.FON 351270 
        ///\MISC\MODELS.PKF 10 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string JAP_D3 {
            get {
                return ResourceManager.GetString("JAP_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 174796 
        ///\1ST_READ.BIN 5054464 
        ///\F355VMOP.BIN 1441792 
        ///\MOVIE.BIN 3895696 
        ///\RELOAD.BIN 660736 
        ///\RPG.BIN 4988928 
        ///\SHMPSPT.BIN 0 
        ///\F355VMOP\CLEAR22A.ADX 2472354 
        ///\F355VMOP\F355.SFD 94625792 
        ///\F355VMOP\GALLERY.BIN 3701248 
        ///\F355VMOP\MOVIE.BIN 327680 
        ///\F355VMOP\OVERLAY.BIN 229376 
        ///\F355VMOP\PACK0.BIN 1884352 
        ///\F355VMOP\SCARL22A.ADX 2321964 
        ///\F355VMOP\SELECT22A.ADX 2313918 
        ///\F355VMOP\SPRITE.BIN 3107328 
        ///\F355VMOP\TEXTURE.BIN 391168 
        ///\FONT\ASCII.PVR 6172 
        ///\FONT\DC_KANA.FON 7680 
        ///\FO [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string JAP_PASS {
            get {
                return ResourceManager.GetString("JAP_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] load {
            get {
                object obj = ResourceManager.GetObject("load", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] mid {
            get {
                object obj = ResourceManager.GetObject("mid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \Default.xbe 5722112 
        ///\burner\ab2.bin 719286 
        ///\burner\ab2.snd 1894368 
        ///\burner\ab2_tex.bin 3145728 
        ///\burner\prog.bin 524288 
        ///\dolby\S2_ADV.aix 12752896 
        ///\dolby\S2_BEAM.aix 3768320 
        ///\dolby\S2_END.aix 28469248 
        ///\dolby\S2_OP.aix 19331072 
        ///\dolby\S2_TOGE.aix 17008640 
        ///\dolby\S2_TOGF.aix 28768256 
        ///\event\DGCT.EV3 22612 
        ///\event\JUMP.EV3 31320 
        ///\event\QESC.EV3 21304 
        ///\fight_mirror\EN_AGON.BIN 1100 
        ///\fight_mirror\EN_BEAR.BIN 540 
        ///\fight_mirror\EN_CHOU.BIN 992 
        ///\fight_mirror\EN_DEKU.BIN 548 
        ///\fight [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string US_2x_DVD {
            get {
                return ResourceManager.GetString("US_2x_DVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 131100 
        ///\1ST_READ.BIN 2695540 
        ///\DISCNUM.BIN 2048 
        ///\FIGHT\EN_RYOU.BIN 7596 
        ///\FONT\ASCII.PVR 6172 
        ///\HANGON\HANGON.BIN 5378124 
        ///\HANGON\HANGON.EMU 849420 
        ///\HARRIER\HARRIER.PKS 2288336 
        ///\MISC\AICADRV.BIN 59264 
        ///\MISC\BATTLE.GZ 34230 
        ///\MISC\BATTLE_E.GZ 34230 
        ///\MISC\BATTLE_F.GZ 33722 
        ///\MISC\BATTLE_G.GZ 34928 
        ///\MISC\BATTLE_S.GZ 34754 
        ///\MISC\BGM110.SND 632148 
        ///\MISC\CM_D000.BIN 629716 
        ///\MISC\CM_JOMO.BIN 21064 
        ///\MISC\CM_MFSY.BIN 329144 
        ///\MISC\COLD.BIN 2414064 
        ///\MISC\COLDINIT.PKF 108715 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string US_D1 {
            get {
                return ResourceManager.GetString("US_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 131100 
        ///\1ST_READ.BIN 2695540 
        ///\DISCNUM.BIN 2048 
        ///\FIGHT\EN_RYOU.BIN 7596 
        ///\FONT\ASCII.PVR 6172 
        ///\HANGON\HANGON.BIN 5378124 
        ///\HANGON\HANGON.EMU 849420 
        ///\HARRIER\HARRIER.PKS 2288336 
        ///\MISC\AICADRV.BIN 59264 
        ///\MISC\BATTLE.GZ 34230 
        ///\MISC\BATTLE_E.GZ 34230 
        ///\MISC\BATTLE_F.GZ 33722 
        ///\MISC\BATTLE_G.GZ 34928 
        ///\MISC\BATTLE_S.GZ 34754 
        ///\MISC\BGM110.SND 632148 
        ///\MISC\CM_D000.BIN 629716 
        ///\MISC\CM_JOMO.BIN 21064 
        ///\MISC\CM_MFSY.BIN 329144 
        ///\MISC\COLD.BIN 2414064 
        ///\MISC\COLDINIT.PKF 108715 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string US_D2 {
            get {
                return ResourceManager.GetString("US_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 131100 
        ///\1ST_READ.BIN 2695540 
        ///\DISCNUM.BIN 2048 
        ///\FIGHT\EN_RYOU.BIN 7596 
        ///\FONT\ASCII.PVR 6172 
        ///\HANGON\HANGON.BIN 5378124 
        ///\HANGON\HANGON.EMU 849420 
        ///\HARRIER\HARRIER.PKS 2288336 
        ///\MISC\AICADRV.BIN 59264 
        ///\MISC\BATTLE.GZ 34230 
        ///\MISC\BATTLE_E.GZ 34230 
        ///\MISC\BATTLE_F.GZ 33722 
        ///\MISC\BATTLE_G.GZ 34928 
        ///\MISC\BATTLE_S.GZ 34754 
        ///\MISC\BGM110.SND 632148 
        ///\MISC\CM_D000.BIN 629716 
        ///\MISC\CM_JOMO.BIN 21064 
        ///\MISC\CM_MFSY.BIN 329144 
        ///\MISC\COLD.BIN 2414064 
        ///\MISC\COLDINIT.PKF 108715 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string US_D3 {
            get {
                return ResourceManager.GetString("US_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \0GDTEX.PVR 131100 
        ///\1ST_READ.BIN 5054464 
        ///\AICADRV.BIN 63432 
        ///\MON.BIN 65552 
        ///\MOVIE.BIN 400128 
        ///\RELOAD.BIN 660736 
        ///\SNDPACK.BIN 97392 
        ///\SP_01.SFD 14462976 
        ///\SP_11.SFD 58628096 
        ///\SP_17.SFD 78546944 
        ///\SP_18.SFD 34596864 
        ///\SP_19.SFD 58929152 
        ///\FONT\ASCII.PVR 6172 
        ///\FONT\DC_KANA.FON 7680 
        ///\FONT\DC_KANJI.FON 351270 
        ///\FONT\RYOU.FON 351270 
        ///\FONT\WAZA.FON 351270 
        ///\MISC\AICADRV.BIN 59264 
        ///\MISC\ASCII.PVR 6172 
        ///\MISC\BATTLE.GZ 36392 
        ///\MISC\BGM110.SND 632148 
        ///\MISC\CM_D000.BIN 629716 
        ///\MISC\C [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string US_PASS {
            get {
                return ResourceManager.GetString("US_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \1ST_READ.BIN 2491396 
        ///\IP.BIN 32768 
        ///\TRACK04.WAV 1032572 
        ///\TRACK05.WAV 27189164 
        ///\TRACK06.WAV 23150780 
        ///\TRACK07.WAV 17207276 
        ///\TRACK08.WAV 2025116 
        ///\2_LINEAR\L80GSEN.IDX 544 
        ///\2_LINEAR\L80GSEN.IMG 2308864 
        ///\2_LINEAR\L80SUSI.IDX 496 
        ///\2_LINEAR\L80SUSI.IMG 1840256 
        ///\2_LINEAR\L80TIKN.IDX 1408 
        ///\2_LINEAR\L80TIKN.IMG 9326816 
        ///\2_LINEAR\L80TOUR.IDX 472 
        ///\2_LINEAR\L80TOUR.IMG 1584640 
        ///\CAMERA\GMOT_CAM.CAM 7508 
        ///\FONT\ASCII.PVR 6172 
        ///\FONT\DC_KANA.FON 7680 
        ///\FONT\DC_KANJI.FON 351270 
        ///\FONT\RYO [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string WS_D1 {
            get {
                return ResourceManager.GetString("WS_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] Wulinshu_Raymonf_Backup {
            get {
                object obj = ResourceManager.GetObject("Wulinshu_Raymonf_Backup", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
